name: CI - CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Push dist folder to another repository
        uses: nkoppel/push-files-to-another-repository@v1.1.2
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'dist/'
          destination-username: 'eloiblt'
          destination-repository: 'eloiblt.github.io'
          destination-branch: main
          commit-email: 'eloi.bellet@gmail.com'